sudo: required
services:
  - docker
install:
  - composer install --optimize-autoloader
script: docker-compose run --rm test
after_success:
  - docker-compose down
  - sudo chmod 777 -R ./build
  - travis_retry php vendor/bin/coveralls -v